[package]
name = "actix-bug-poc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.1"
actix-multipart = "0.4.0"
env_logger = "0.9.0"
futures-util = "0.3.21"
